'use client';
import {useState} from 'react';
import {useTranslations} from 'next-intl';
import {Menu, Users, ShieldCheck, Handshake, House, Building2, MapPin, HardHat} from 'lucide-react';
import {Link} from '@/i18n/navigation';
import {projects} from '@/lib/content';

export default function Site(){
 const t=useTranslations(); const [open,setOpen]=useState(false);
 return <>
  <header className="header"><div className="container nav"><Link href="/" className="logo"><span className="logoMark">IP</span><span className="logoText"><span>IDEAL POINT</span><span>ELECTRIC</span></span></Link><nav className="navLinks">{['home','about','services','projects','commercial','residential','multifamily','contact'].map(x=><Link key={x} href={x==='home'?'/':`/#${x}`}>{t(`nav.${x}`)}</Link>)}<a className="goldBtn" href="#contact">{t('nav.request')}</a></nav><button className="mobileMenu" aria-label="Menu" onClick={()=>setOpen(!open)}><Menu size={20}/></button></div>{open&&<div style={{position:'absolute',top:68,left:0,right:0,background:'#080808',padding:20,borderBottom:'1px solid #333'}}>{['home','about','services','projects','commercial','residential','multifamily','contact'].map(x=><Link onClick={()=>setOpen(false)} style={{display:'block',padding:'12px 0',textTransform:'uppercase',fontSize:12}} key={x} href={x==='home'?'/':`/#${x}`}>{t(`nav.${x}`)}</Link>)}</div>}</header>
  <main>
   <section className="hero"><div className="container"><div className="heroContent"><div className="eyebrow">{t('hero.eyebrow')}</div><h1>{t('hero.title')}</h1><p>{t('hero.description')}</p><div className="actions"><a className="goldBtn" href="#projects">{t('hero.projects')} →</a><a className="outlineBtn" href="#contact">{t('hero.bid')}</a></div><div className="badges"><div className="badge"><ShieldCheck size={18}/> {t('hero.licensed')}</div><div className="badge"><HardHat size={18}/> {t('hero.experience')}</div><div className="badge">◉ {t('hero.safety')}</div></div></div></div></section>
   <section id="about" className="section light"><div className="container aboutGrid"><div><div className="eyebrow">{t('about.eyebrow')}</div><h2 className="sectionTitle">{t('about.title')}</h2><p className="body">{t('about.body')}</p><a className="goldBtn" href="#contact">{t('about.learn')} →</a></div><div className="features"><Feature icon={<Users/>} title={t('about.teamTitle')} body={t('about.teamBody')}/><Feature icon={<ShieldCheck/>} title={t('about.qualityTitle')} body={t('about.qualityBody')}/><Feature icon={<Handshake/>} title={t('about.clientTitle')} body={t('about.clientBody')}/></div></div></section>
   <section id="services" className="section dark"><div className="container"><div className="sectionHead"><div><div className="eyebrow">{t('services.eyebrow')}</div><h2 className="sectionTitle">{t('services.title')}</h2></div><p className="body" style={{maxWidth:420}}>{t('services.intro')}</p></div><div className="servicesGrid"><Service image="/images/residential.jpg" icon={<House/>} title={t('services.resTitle')} items={t.raw('services.resItems')}/><Service image="/images/commercial.jpg" icon={<Building2/>} title={t('services.comTitle')} items={t.raw('services.comItems')}/><Service image="/images/multifamily.jpg" icon={<Building2/>} title={t('services.multiTitle')} items={t.raw('services.multiItems')}/></div></div></section>
   <section id="projects" className="section light"><div className="container"><div className="sectionHead"><div><div className="eyebrow">{t('projects.eyebrow')}</div><h2 className="sectionTitle">{t('projects.title')}</h2></div><a className="outlineBtn" style={{color:'#111',borderColor:'#111'}} href="#projects">{t('projects.all')}</a></div><div className="projectsGrid">{projects.map(p=><article className="project" key={p.key}><div className="projectImg" style={{backgroundImage:`url(${p.image})`}}/><div className="projectBody"><h3>{t(`projects.${p.key}`)}</h3><p>{t(`projects.${p.type}`)}</p><a href="#contact">{t('projects.view')} →</a></div></article>)}</div></div></section>
   <section className="stats"><div className="container statsGrid"><Stat icon={<HardHat/>} num="16+" label={t('stats.experience')}/><Stat icon={<ShieldCheck/>} num="LICENSED" label={t('stats.licensed')}/><Stat icon={<Users/>} num="100+" label={t('stats.projects')}/><Stat icon={<MapPin/>} num="YVR" label={t('stats.area')}/></div></section>
   <section id="contact" className="section cta"><div className="container ctaGrid"><div><div className="eyebrow">{t('nav.contact')}</div><h2>{t('cta.title')}</h2><p className="body">{t('cta.body')}</p></div><form className="form" action="mailto:info@idealpointelectric.ca" method="post" encType="text/plain"><input required name="name" placeholder={t('cta.name')}/><input name="company" placeholder={t('cta.company')}/><input required type="email" name="email" placeholder={t('cta.email')}/><input name="phone" placeholder={t('cta.phone')}/><textarea name="message" placeholder={t('cta.message')}/><button className="goldBtn" type="submit">{t('cta.submit')}</button></form></div></section>
  </main>
  <footer className="footer"><div className="container"><div className="footerGrid"><div><div className="logo"><span className="logoMark">IP</span><span className="logoText"><span>IDEAL POINT</span><span>ELECTRIC</span></span></div><p style={{marginTop:18}}>{t('footer.description')}</p></div><FooterCol title={t('footer.company')} links={['about','team','careers','safety']}/><FooterCol title={t('footer.services')} links={['residential','commercial','multifamily','maintenance']}/><FooterCol title={t('footer.resources')} links={['projects','faq','contactLink']}/><div><h4>{t('footer.contact')}</h4><p>{t('footer.address')}</p><p>{t('footer.area')}</p><p>604.309.1234</p><p>info@idealpointelectric.ca</p></div></div><div className="copyright">{t('footer.copyright')}</div></div></footer>
 </>
}
function Feature({icon,title,body}:{icon:React.ReactNode;title:string;body:string}){return <div className="feature"><div className="icon">{icon}</div><h3>{title}</h3><p>{body}</p></div>}
function Service({image,icon,title,items}:{image:string;icon:React.ReactNode;title:string;items:string[]}){return <article className="serviceCard"><div className="serviceImage" style={{backgroundImage:`url(${image})`}}/><div className="serviceBody"><div className="icon">{icon}</div><h3>{title}</h3><ul>{items.map(i=><li key={i}>{i}</li>)}</ul><a className="textLink" href="#contact">Learn More →</a></div></article>}
function Stat({icon,num,label}:{icon:React.ReactNode;num:string;label:string}){return <div className="stat"><div className="icon">{icon}</div><div><div className="statNum">{num}</div><div className="statLabel">{label}</div></div></div>}
function FooterCol({title,links}:{title:string;links:string[]}){const t=useTranslations('footer'); return <div><h4>{title}</h4>{links.map(l=><a href="#" key={l}>{t(l)}</a>)}</div>}
